name: SmeltingBook
version: ${project.version}
main: digital.mywafiuis.smeltingbook.SmeltingBook
api-version: 1.13

commands:

  smeltingbook:
    description: Gives selected player a Smelting I book.
    usage: /smeltingbook <player>